services:
  master:
    build:
      context: src/master
    container_name: master
    ports:
      - "5000:5000"
    depends_on:
      - slave_letters
      - slave_numbers

  slave_letters:
    build:
      context: src/slaveLetters
    container_name: slave_letters
    ports:
      - "8001:8001"

  slave_numbers:
    build:
      context: src/slaveNumbers
    container_name: slave_numbers
    ports:
      - "8002:8002"
